name: ComplexInteractions
version: '1.0'
main: org.frags.complexInteractions.ComplexInteractions
api-version: '1.21'
depend:
  - Vault
  - PlaceholderAPI
  - CustomItems
softdepend:
  - FancyNpcs
  - Oraxen
  - MMOItems
  - ItemsAdder
commands:
  interactions:
    description: "Main command of the plugin"
  gethead:
    description: "gets head"
  mission:
    description: "Open mission menu"
    aliases:
      - mision
      - misión
      - misiones
      - missions